# Generated by Django 5.1.6 on 2025-04-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID from filters.json', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Ta'lim yo'nalishi")),
            ],
            options={
                'verbose_name': "Ta'lim Yo'nalishi",
                'verbose_name_plural': "Ta'lim Yo'nalishlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default="Noma'lum Daraja", max_length=100, unique=True, verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
            },
        ),
        migrations.CreateModel(
            name='EducationLanguage',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID from filters.json', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Ta'lim tili")),
            ],
            options={
                'verbose_name': "Ta'lim Tili",
                'verbose_name_plural': "Ta'lim Tillari",
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID from filters.json', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Ta'lim turi")),
            ],
            options={
                'verbose_name': "Ta'lim Turi",
                'verbose_name_plural': "Ta'lim Turlari",
            },
        ),
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID from filters.json', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='OTM turi')),
            ],
            options={
                'verbose_name': 'OTM Turi',
                'verbose_name_plural': 'OTM Turlari',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ID from filters.json', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Original ID from JSON', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq nomi")),
                ('slug', models.SlugField(blank=True, help_text='URL uchun qisqa nom', max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, help_text="Logo fayl yo'li", max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('about_grant', models.TextField(blank=True, null=True, verbose_name='Grant haqida')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('founded_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tashkil etilgan yili')),
                ('students_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Talabalar soni')),
                ('current_quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='Joriy kvota')),
                ('has_accomodation', models.BooleanField(default=False, verbose_name='Yotoqxona mavjudmi?')),
                ('has_grant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Grant mavjudmi?')),
                ('admission_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qabul telefoni')),
                ('web_site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Veb-sayt')),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('facebook_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('youtube_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube')),
                ('support_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name="Qo'llab-quvvatlash Emaili")),
                ('admission_start_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qabul boshlanish sanasi')),
                ('admission_deadline', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qabul tugash sanasi')),
                ('minimal_tuition_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimal kontrakt narxi')),
                ('maximal_tuition_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal kontrakt narxi')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kenglik')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uzunlik')),
                ('is_open_for_admission', models.BooleanField(default=False, verbose_name='Qabul ochiqmi?')),
                ('rating', models.CharField(blank=True, max_length=10, null=True, verbose_name='Reyting')),
                ('rating_total_pupil', models.PositiveIntegerField(blank=True, null=True, verbose_name="Reytingdagi o'quvchilar soni")),
                ('mtdt_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Sarlavha')),
                ('mtdt_description', models.TextField(blank=True, null=True, verbose_name='Meta Tavsif')),
                ('direction_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="Yo'nalishlar soni")),
                ('degrees', models.ManyToManyField(blank=True, to='web.degree', verbose_name='Darajalar')),
                ('education_languages', models.ManyToManyField(blank=True, to='web.educationlanguage', verbose_name="Ta'lim Tillari")),
                ('education_types', models.ManyToManyField(blank=True, to='web.educationtype', verbose_name="Ta'lim Turlari")),
                ('institution_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.institutioncategory', verbose_name='OTM Turi')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.location', verbose_name='Asosiy Manzil')),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('direction_id', models.PositiveIntegerField(help_text='Original direction_id from JSON', primary_key=True, serialize=False)),
                ('direction_name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('direction_slug', models.SlugField(blank=True, help_text='URL uchun qisqa nom', max_length=255, unique=True)),
                ('direction_description', models.TextField(blank=True, null=True, verbose_name="Yo'nalish tavsifi")),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Talablar')),
                ('first_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birinchi fan')),
                ('second_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikkinchi fan')),
                ('has_mandatory_subjects', models.BooleanField(blank=True, default=False, null=True, verbose_name='Majburiy fanlar bormi?')),
                ('has_stipend', models.BooleanField(default=False, verbose_name='Stipendiya mavjudmi?')),
                ('is_open_for_admission', models.BooleanField(default=False, verbose_name='Qabul ochiqmi?')),
                ('application_start_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ariza topshirish boshlanish sanasi')),
                ('application_deadline', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ariza topshirish tugash sanasi')),
                ('status', models.CharField(blank=True, default='active', max_length=50, null=True, verbose_name='Holati')),
                ('is_promoted', models.IntegerField(blank=True, default=0, null=True, verbose_name="Targ'ib qilinganmi?")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name="Ta'lim Yo'nalishi Kategoriyasi")),
                ('degrees', models.ManyToManyField(blank=True, to='web.degree', verbose_name='Darajalar')),
                ('education_languages', models.ManyToManyField(blank=True, to='web.educationlanguage', verbose_name="Ta'lim Tillari")),
                ('education_types', models.ManyToManyField(blank=True, to='web.educationtype', verbose_name="Ta'lim Turlari")),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='web.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['university__full_name', 'direction_name'],
            },
        ),
    ]
