# Generated by Django 5.1.6 on 2025-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='direction_count',
        ),
        migrations.RemoveField(
            model_name='university',
            name='mtdt_description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='mtdt_title',
        ),
        migrations.RemoveField(
            model_name='university',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='rating_total_pupil',
        ),
        migrations.AddField(
            model_name='university',
            name='license_file',
            field=models.FileField(blank=True, help_text='License file', null=True, upload_to='license_files/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.PositiveIntegerField(help_text='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.FileField(blank=True, help_text="Logo fayl yo'li", null=True, upload_to='university_logos/'),
        ),
    ]
