# Generated by Django 5.1.6 on 2025-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_university_direction_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Gallery image', null=True, upload_to='gallery_images/')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='web.gallery', verbose_name='Galereya'),
        ),
    ]
