# Generated by Django 5.1.6 on 2025-05-02 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gallery_university_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Yo'nalish tavsifi"),
        ),
        migrations.AlterField(
            model_name='direction',
            name='requirement',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about_grant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Grant haqida'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
