# Generated by Django 5.1.6 on 2025-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_direction_direction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ariza topshirish tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='application_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ariza topshirish boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='university',
            name='admission_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='university',
            name='admission_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul boshlanish sanasi'),
        ),
    ]
