# Generated by Django 5.1.6 on 2025-05-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_direction_application_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='university',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='web.university'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('local_tuition_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('international_tuition_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='web.direction')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.educationtype')),
            ],
            options={
                'unique_together': {('direction', 'education_type')},
            },
        ),
    ]
