# Generated by Django 5.2 on 2025-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_university_gallery_gallery_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='founded_year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tashkil etilgan yili'),
        ),
    ]
