# Generated by Django 5.2 on 2025-05-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_university_founded_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuitionfee',
            options={'verbose_name': 'Kontrakt narxi', 'verbose_name_plural': 'Kontrakt narxlari'},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='direction_id',
        ),
        migrations.AddField(
            model_name='direction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='educationlanguage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institutioncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name="O'quv yili"),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='education_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.educationtype', verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='international_tuition_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Xalqaro kontrakt narxi'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='local_tuition_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahalliy kontrakt narxi'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
