# Generated by Django 5.2 on 2025-05-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_tuitionfee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuitionfee',
            options={'ordering': ['local_tuition_fee'], 'verbose_name': 'Kontrakt narxi', 'verbose_name_plural': 'Kontrakt narxlari'},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='university',
            name='current_quota',
        ),
        migrations.RemoveField(
            model_name='university',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='university',
            name='students_count',
        ),
    ]
