# Generated by Django 5.2 on 2025-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_tuitionfee_options_remove_direction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='has_grant',
            field=models.BooleanField(default=False, verbose_name='Grant mavjudmi?'),
        ),
    ]
